version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hxdnmivlny6e"
s3_prefix = "hello-world-python"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "IdentityNameParameter=\"\""
image_repositories = []
