version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-gateway-authorizer-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ido7lmxzlpqa"
s3_prefix = "api-gateway-authorizer-python"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TopicNameParameter=\"\""
image_repositories = []
